// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAnQxA8_Grn9smG85s_ErW1-96XZ7UCXw',
    appId: '1:374010154862:web:fee5ce390ac36a32c7bb7f',
    messagingSenderId: '374010154862',
    projectId: 'one-life-time-tracker',
    authDomain: 'one-life-time-tracker.firebaseapp.com',
    databaseURL: 'https://one-life-time-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'one-life-time-tracker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC_GVWiFMuTHJJYAzrx6zGeTm3qL7HUII',
    appId: '1:374010154862:android:3716ebe79dab6988c7bb7f',
    messagingSenderId: '374010154862',
    projectId: 'one-life-time-tracker',
    databaseURL: 'https://one-life-time-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'one-life-time-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7fwukH2aDU5km0Y87rLrHjxQe01iH5Do',
    appId: '1:374010154862:ios:10cd2488069d9227c7bb7f',
    messagingSenderId: '374010154862',
    projectId: 'one-life-time-tracker',
    databaseURL: 'https://one-life-time-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'one-life-time-tracker.appspot.com',
    iosClientId: '374010154862-1lrimr8vtn7lbfkhdvgpi4onej6kb6b1.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeeTimeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7fwukH2aDU5km0Y87rLrHjxQe01iH5Do',
    appId: '1:374010154862:ios:10cd2488069d9227c7bb7f',
    messagingSenderId: '374010154862',
    projectId: 'one-life-time-tracker',
    databaseURL: 'https://one-life-time-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'one-life-time-tracker.appspot.com',
    iosClientId: '374010154862-1lrimr8vtn7lbfkhdvgpi4onej6kb6b1.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeeTimeTracker',
  );
}
