// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqmc1ZvyX40FLWheua707HoWBgmjNWWHU',
    appId: '1:87797584274:web:06a35ef62d2d657bb3b14b',
    messagingSenderId: '87797584274',
    projectId: 'timetracker-31f94',
    authDomain: 'timetracker-31f94.firebaseapp.com',
    storageBucket: 'timetracker-31f94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGAD9_qc_OBhPQ_cDCpCjuCUG-nB6xgNA',
    appId: '1:87797584274:android:6c03cb4c4489247cb3b14b',
    messagingSenderId: '87797584274',
    projectId: 'timetracker-31f94',
    storageBucket: 'timetracker-31f94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2ueZK-Db4RILbwe4fhs7oYuc_4aeKwPY',
    appId: '1:87797584274:ios:2807a12277e65ea0b3b14b',
    messagingSenderId: '87797584274',
    projectId: 'timetracker-31f94',
    storageBucket: 'timetracker-31f94.appspot.com',
    iosClientId:
        '87797584274-uf5dr0p5pearlij6q2i5ogh115ghp05j.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeeTimeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2ueZK-Db4RILbwe4fhs7oYuc_4aeKwPY',
    appId: '1:87797584274:ios:2807a12277e65ea0b3b14b',
    messagingSenderId: '87797584274',
    projectId: 'timetracker-31f94',
    storageBucket: 'timetracker-31f94.appspot.com',
    iosClientId:
        '87797584274-uf5dr0p5pearlij6q2i5ogh115ghp05j.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeeTimeTracker',
  );
}
